version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
      args:
        user_name: ${user_name}
        user_email: ${user_email}
    ports:
      - "9000:9000"
    env_file:
      - .env
    environment:
      - ZENN_DIR=/app/zenn
      - GITHUB_PAT=${GITHUB_PAT}
      - GITHUB_USER=${GITHUB_USER}
      - user_name=${user_name}
      - user_email=${user_email}
    volumes:
      - .:/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 9000 --reload
